code_example:
  snippet_folder_name: code-example
  section_folder_name: sections
languages:
  js:
    fullname: javascript
    ext: js
    sdk_url: https://github.com/kuzzleio/sdk-javascript.git
    sdk_branch: master
  go:
    fullname: go
    ext: go
    sdk_url: https://github.com/kuzzleio/sdk-go.git
    sdk_branch: 1.x
  cpp:
    fullname: cpp
    ext: cpp
    sdk_url: https://github.com/kuzzleio/sdk-go.git
    sdk_branch: 1.x
  java:
    fullname: Java
    ext: java
    sdk_url: https://github.com/kuzzleio/sdk-go.git
    sdk_branch: 1.x